//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long empId { get; set; }
        public string fName { get; set; }
        public string mName { get; set; }
        public string lName { get; set; }
        public Nullable<short> age { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<short> gender { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string hobby { get; set; }
    }
}
