//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public long salaryId { get; set; }
        public long empId { get; set; }
        public System.DateTime date { get; set; }
        public decimal sal { get; set; }
    }
}
